# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ISNaWdvO7oxkjIkMHd4PkoZUUI6C46je
"""

import pandas as pd

# 1. Definimos el mapa de rutas basado exactamente en tus archivos
rutas_archivos = {
    2022: "/content/2022 Condiciones de vida del hogar y tenencia de bienes.CSV",
    2023: "/content/2023 Condiciones de vida del hogar y tenencia de bienes.CSV",
    2024: "/content/2024 Condiciones de vida del hogar y tenencia de bienes.CSV",
    2025: "/content/2025 Condiciones de vida del hogar y tenencia de bienes.csv"
}

# Diccionario vacío para almacenar los DataFrames temporales
dfs_anuales = {}

# 2. Bucle para importar y marcar cada año automáticamente
for anio, ruta in rutas_archivos.items():
    try:
        # Cargamos el CSV con el estándar del DANE
        df_temporal = pd.read_csv(
            ruta,
            sep=";",             # Delimitador típico del DANE
            encoding="latin-1",  # Protege eñes y tildes
            dtype=str            # Conserva intactas las llaves como DIRECTORIO y códigos de variables
        )

        # Creamos la columna de control temporal
        df_temporal['ANIO'] = str(anio)

        # Guardamos en nuestro diccionario
        dfs_anuales[anio] = df_temporal
        print(f"✅ ¡Año {anio} importado correctamente! Dimensiones: {df_temporal.shape}")

    except Exception as e:
        print(f"❌ Error al cargar el año {anio}: {e}")
        print("Tip: Si sale error de delimitador, avísame para probar cambiando sep=';' por sep=','")

# 1. Definimos la lista exacta de variables que queremos conservar para el análisis
columnas_proyecto = [
    'DIRECTORIO', 'SECUENCIA_P', 'FEX_C', 'ANIO',
    'P5230', 'P9090', 'P3202S1', 'P3202S10', 'P3203S10',
    'P1077S2', 'P1913S10', 'P1913S9',
    'P3516S1', 'P3516S2', 'P3516S3', 'P3516S4',
    'P3516S5', 'P3516S6', 'P3516S7', 'P3516S8'
]

dfs_listos = []

# 2. Filtramos cada año antes de concatenar
for anio, df in dfs_anuales.items():
    # Buscamos la intersección real (columnas de la lista que sí existen en este año)
    columnas_presentes = [col for col in columnas_proyecto if col in df.columns]

    # Extraemos solo esas columnas
    df_filtrado = df[columnas_presentes].copy()
    dfs_listos.append(df_filtrado)

# 3. Concatenamos verticalmente todos los años
df_historico = pd.concat(dfs_listos, ignore_index=True)

print(f"📊 ¡Fusión histórica completada con éxito!")
print(f"Filas totales acumuladas: {df_historico.shape[0]:,}")
print(f"Columnas analíticas conservadas: {df_historico.shape[1]}")
print(f"\nConteo de registros por año en el nuevo dataset:")
print(df_historico['ANIO'].value_counts().sort_index())

# 1. Inspeccionamos las respuestas de la primera pregunta de la escala FIES
print("Respuestas crudas en P3516S1 (Preocupación por quedarse sin comida):")
print(df_historico['P3516S1'].value_counts(dropna=False))

# 2. Inspeccionamos la variable de pobreza subjetiva
print("\nRespuestas crudas en P5230 (¿Se considera pobre?):")
print(df_historico['P5230'].value_counts(dropna=False))

import numpy as np

# 1. Copiamos el dataset original para proteger los datos crudos
df_limpio = df_historico.copy()

# 2. Definimos el diccionario de mapeo
mapeo_binario = {'1': 1, '2': 0, '3': np.nan}

# Listamos las 8 columnas de la escala FIES
columnas_fies = [f'P3516S{i}' for i in range(1, 9)]

# 3. Aplicamos la transformación a las variables FIES y a la Pobreza Subjetiva
for col in columnas_fies:
    df_limpio[col] = df_limpio[col].map(mapeo_binario)

df_limpio['P5230'] = df_limpio['P5230'].map({'1': 1, '2': 0})

# 4. Convertimos el Factor de Expansión (FEX_C) a numérico flotante para los cálculos de peso
df_limpio['FEX_C'] = pd.to_numeric(df_limpio['FEX_C'], errors='coerce')

# 5. Creamos la columna calculada: PUNTAJE_FIES (Suma de las 8 preguntas)
df_limpio['PUNTAJE_FIES'] = df_limpio[columnas_fies].sum(axis=1, skipna=True)

# 6. Creamos la variable objetivo final: Inseguridad Alimentaria Grave (PIAG)
# Según el DANE, es grave si respondieron 'Sí' (1) a la pregunta más extrema (P3516S8)
df_limpio['INSEGURIDAD_GRAVE'] = df_limpio['P3516S8'].astype(float)

print("✅ ¡Transformación binaria e indicadores creados con éxito!")
print("\nDistribución del Puntaje FIES en la muestra histórica (0 al 8):")
print(df_limpio['PUNTAJE_FIES'].value_counts().sort_index())

# 1. Definimos las variables que se limpian con el formato binario (1=Sí, 0=No)
columnas_binarias_x = [
    'P3202S1',   # Jefe perdió empleo
    'P3202S10',  # Atraso en servicios públicos
    'P3203S10',  # Estrategia: Disminuir gasto en alimentos
    'P1077S2'    # Posee nevera o refrigerador
]

for col in columnas_binarias_x:
    if col in df_limpio.columns:
        df_limpio[col] = df_limpio[col].map({'1': 1, '2': 0}).fillna(0).astype(int)

# 2. Convertimos las variables de tiempo de acceso (P1913) a numéricas
columnas_tiempo = ['P1913S10', 'P1913S9']
for col in columnas_tiempo:
    if col in df_limpio.columns:
        df_limpio[col] = pd.to_numeric(df_limpio[col], errors='coerce')

# 3. Inspeccionamos cómo quedó nuestro dataset analítico final
print("✅ ¡Variables predictoras alineadas y optimizadas!")
print(df_limpio[['ANIO', 'PUNTAJE_FIES', 'P5230', 'P1077S2', 'FEX_C']].head())

# 1. Vamos a espiar cómo viene el texto original de FEX_C en 2025
fex_crudo_2025 = df_historico[df_historico['ANIO'] == '2025']['FEX_C']
print("Muestra de datos crudos de FEX_C en 2025:")
print(fex_crudo_2025.head())

# 2. Aplicamos un parche robusto: reemplazamos comas por puntos por si acaso
df_limpio['FEX_C_REPARADO'] = df_historico['FEX_C'].astype(str).str.replace(',', '.', regex=False)
df_limpio['FEX_C_REPARADO'] = pd.to_numeric(df_limpio['FEX_C_REPARADO'], errors='coerce')

# ============================================================
# PASO QUE FALTABA: Construcción de PIAG_DUMMY y PIAMG_DUMMY
# ============================================================
# El DANE no publica un punto de corte fijo sobre PUNTAJE_FIES: clasifica la
# severidad con un modelo estadístico Rasch/IRT calibrado sobre las 8 preguntas,
# no con una sola pregunta ni con una suma simple. Como aproximación transparente
# (sin implementar el modelo Rasch completo), calibramos el umbral de PUNTAJE_FIES
# (0-8) que mejor reproduce las tasas NACIONALES oficiales publicadas por el DANE:
#   Moderada o grave: 2022=28.1%, 2023=26.1%, 2024=25.5%, 2025=21.1%
#   Grave:            2022=4.9%,                          2025=3.4%
# IMPORTANTE: esto es un proxy calibrado, no el cálculo oficial del DANE.
# Documentar esta decisión metodológica en el README del proyecto.

oficial_moderada_o_grave = {'2022': 28.1, '2023': 26.1, '2024': 25.5, '2025': 21.1}
oficial_grave = {'2022': 4.9, '2025': 3.4}

def tasa_ponderada_por_umbral(umbral):
    dummy = (df_limpio['PUNTAJE_FIES'] >= umbral).astype(int)
    numerador = (dummy * df_limpio['FEX_C_REPARADO']).groupby(df_limpio['ANIO']).sum()
    denominador = df_limpio.groupby('ANIO')['FEX_C_REPARADO'].sum()
    return numerador / denominador * 100

def calibrar_umbral(oficial_dict, etiqueta):
    mejor_umbral, menor_error = None, float('inf')
    print(f"\n🔎 Calibrando umbral para: {etiqueta}")
    for umbral in range(1, 9):
        calculado = tasa_ponderada_por_umbral(umbral)
        error = sum((calculado[a] - v) ** 2 for a, v in oficial_dict.items() if a in calculado.index)
        print(f"  Umbral >= {umbral}: error cuadrático = {error:.2f}")
        if error < menor_error:
            mejor_umbral, menor_error = umbral, error
    print(f"👉 Mejor umbral encontrado para {etiqueta}: PUNTAJE_FIES >= {mejor_umbral}")
    return mejor_umbral

umbral_piamg = calibrar_umbral(oficial_moderada_o_grave, "Moderada o grave")
umbral_piag = calibrar_umbral(oficial_grave, "Grave")

df_limpio['PIAMG_DUMMY'] = (df_limpio['PUNTAJE_FIES'] >= umbral_piamg).astype(int)
df_limpio['PIAG_DUMMY'] = (df_limpio['PUNTAJE_FIES'] >= umbral_piag).astype(int)

print("\n✅ PIAG_DUMMY y PIAMG_DUMMY creados. Umbrales calibrados contra cifras oficiales del DANE.")

# 3. Volvemos a correr la agrupación con el factor reparado
def media_ponderada_piamg_rep(group):
    return (group['PIAMG_DUMMY'] * group['FEX_C_REPARADO']).sum() / group['FEX_C_REPARADO'].sum() * 100

def media_ponderada_piag_rep(group):
    return (group['PIAG_DUMMY'] * group['FEX_C_REPARADO']).sum() / group['FEX_C_REPARADO'].sum() * 100

tendencia_reparada = df_limpio.groupby('ANIO').apply(
    lambda x: pd.Series({
        'Prevalencia_Moderada_Grave_%': media_ponderada_piamg_rep(x),
        'Prevalencia_Grave_%': media_ponderada_piag_rep(x),
        'Total_Hogares_Expandidos': x['FEX_C_REPARADO'].sum()
    }), include_groups=False
).reset_index()

print("\n📊 TENDENCIA HISTÓRICA REPARADA:")
print(tendencia_reparada.to_string(index=False))

# Reemplazamos la columna FEX_C original con la versión reparada y limpia
df_limpio['FEX_C'] = df_limpio['FEX_C_REPARADO']
# Eliminamos la columna temporal para dejar el DataFrame impecable
df_limpio = df_limpio.drop(columns=['FEX_C_REPARADO'])

import pandas as pd
import os

# 1. Definimos las rutas de tus archivos de vivienda
rutas_vivienda = {
    2022: "/content/2022 Datos de la vivienda.csv",
    2023: "/content/2023 Datos de la vivienda.csv",
    2024: "/content/2024 Datos de la vivienda.csv",
    2025: "/content/2025 Datos de la vivienda.csv"
}

# Validación de mayúsculas/minúsculas en las extensiones (.csv vs .CSV)
for anio, ruta in rutas_vivienda.items():
    if not os.path.exists(ruta) and os.path.exists(ruta.replace('.csv', '.CSV')):
        rutas_vivienda[anio] = ruta.replace('.csv', '.CSV')

dfs_vivienda_listos = []

# 2. Bucle inteligente para procesar cada año
for anio, ruta in rutas_vivienda.items():
    try:
        # Leemos con el separador verificado ';'
        df_viv = pd.read_csv(ruta, sep=";", encoding="latin-1", dtype=str)

        # Forzamos columnas a mayúsculas
        df_viv.columns = df_viv.columns.str.upper()

        # Buscador inteligente de la columna geográfica
        col_encontrada = None
        for posible_columna in ['P1_DEPARTAMENTO', 'P1_DEPARTA', 'DPTO']:
            if posible_columna in df_viv.columns:
                col_encontrada = posible_columna
                break

        if col_encontrada is None:
            raise KeyError(f"No se encontró ninguna columna geográfica. Columnas disponibles: {list(df_viv.columns[:6])}")

        # Extraemos las llaves y renombramos la columna a 'DPTO'
        df_viv_filtrado = df_viv[['DIRECTORIO', col_encontrada]].copy()
        df_viv_filtrado = df_viv_filtrado.rename(columns={col_encontrada: 'DPTO'})
        df_viv_filtrado['ANIO'] = str(anio)

        # Eliminamos duplicados por vivienda
        df_viv_filtrado = df_viv_filtrado.drop_duplicates(subset=['DIRECTORIO', 'ANIO'])

        dfs_vivienda_listos.append(df_viv_filtrado)
        print(f"✅ Año {anio} procesado con éxito usando la columna: '{col_encontrada}'")

    except Exception as e:
        print(f"❌ Error fatal en el año {anio}: {e}")

# 3. Consolidamos el maestro geográfico histórico
df_geo_historico = pd.concat(dfs_vivienda_listos, ignore_index=True)

# Limpieza preventiva si la columna DPTO ya existía de intentos fallidos
if 'DPTO' in df_limpio.columns:
    df_limpio = df_limpio.drop(columns=['DPTO'])

# 4. El LEFT JOIN definitivo
df_limpio = pd.merge(
    df_limpio,
    df_geo_historico,
    on=['DIRECTORIO', 'ANIO'],
    how='left'
)

print("\n📊 ¡CRUCE GEOGRÁFICO HISTÓRICO COMPLETADO!")
print(f"Dimensiones finales de tu dataset: {df_limpio.shape}")
print("\nValidación de registros sin geografía por año (El objetivo dorado es que todos digan 0):")
print(df_limpio.groupby('ANIO')['DPTO'].apply(lambda x: x.isna().sum()))

# 1. Diccionario oficial DIVIPOLA para mapear los códigos del DANE
divipola = {
    '05': 'Antioquia', '08': 'Atlántico', '11': 'Bogotá', '13': 'Bolívar', '15': 'Boyacá',
    '17': 'Caldas', '18': 'Caquetá', '19': 'Cauca', '20': 'Cesar', '23': 'Córdoba',
    '25': 'Cundinamarca', '27': 'Chocó', '41': 'Huila', '44': 'La Guajira', '47': 'Magdalena',
    '50': 'Meta', '52': 'Nariño', '54': 'Norte de Santander', '63': 'Quindío', '66': 'Risaralda',
    '68': 'Santander', '70': 'Sucre', '73': 'Tolima', '76': 'Valle del Cauca', '81': 'Arauca', '85': 'Casanare',
    '86': 'Putumayo', '88': 'San Andrés', '91': 'Amazonas', '94': 'Guainía', '95': 'Guaviare',
    '97': 'Vaupés', '99': 'Vichada'
}

# Normalizamos el código antes de mapear: algunos años exportan '5' en vez de '05',
# lo que hace que el mapeo falle silenciosamente y deje el código crudo (5, 8...)
# en vez del nombre del departamento. zfill(2) rellena con cero a la izquierda
# sin afectar los códigos que ya vienen con 2 dígitos.
# Solo tocamos los valores no nulos, para no convertir un DPTO faltante (NaN)
# en el texto literal "nan".
mascara_no_nulo = df_limpio['DPTO'].notna()
df_limpio.loc[mascara_no_nulo, 'DPTO'] = (
    df_limpio.loc[mascara_no_nulo, 'DPTO'].astype(str).str.strip().str.zfill(2)
)

# Asignamos los nombres reales de los departamentos
df_limpio['NOMBRE_DPTO'] = df_limpio['DPTO'].map(divipola).fillna(df_limpio['DPTO'])

# 2. Filtramos para analizar la foto más reciente: el año 2025
df_2025 = df_limpio[df_limpio['ANIO'] == '2025'].copy()

# 3. Calculamos la tasa ponderada de Inseguridad Alimentaria Grave por región
ranking_dpto = df_2025.groupby('NOMBRE_DPTO').apply(
    lambda x: pd.Series({
        'Inseguridad_Grave_%': (x['PIAG_DUMMY'] * x['FEX_C']).sum() / x['FEX_C'].sum() * 100,
        'Muestra_Hogares_Encuestados': len(x)
    }), include_groups=False
).reset_index()

# 4. Ordenamos de mayor a menor criticidad
ranking_dpto = ranking_dpto.sort_values(by='Inseguridad_Grave_%', ascending=False)

print("🚨 TOP 10 DEPARTAMENTOS CON MAYOR INSEGURIDAD ALIMENTARIA GRAVE (2025):")
print(ranking_dpto.head(10).to_string(index=False))

print("\n🟢 TOP 5 DEPARTAMENTOS CON MENOR INSEGURIDAD ALIMENTARIA GRAVE (2025):")
print(ranking_dpto.tail(5).to_string(index=False))

import pandas as pd
import os

# 1. Definimos las rutas con el nombre exacto de tu módulo
rutas_composicion = {
    2022: "/content/2022 Caracteristicas y composicion del hogar.CSV",
    2023: "/content/2023 Características y composición del hogar.csv",
    2024: "/content/2024 Características y composición del hogar.csv",
    2025: "/content/2025 Características y composición del hogar.csv"
}

# Validación preventiva de extensiones (.csv vs .CSV)
for anio, ruta in rutas_composicion.items():
    if not os.path.exists(ruta) and os.path.exists(ruta.replace('.csv', '.CSV')):
        rutas_composicion[anio] = ruta.replace('.csv', '.CSV')

dfs_jefes_listos = []

# 2. Procesamos cada año identificando dinámicamente el parentesco
for anio, ruta in rutas_composicion.items():
    try:
        df_pers = pd.read_csv(ruta, sep=";", encoding="latin-1", dtype=str)
        df_pers.columns = df_pers.columns.str.upper()

        # BUSCADOR INTELIGENTE DE PARENTESCO: Detecta si es P6050 o P6051
        col_parentesco = None
        for col_p in ['P6050', 'P6051']:
            if col_p in df_pers.columns:
                col_parentesco = col_p
                break

        if col_parentesco is None:
            raise KeyError(f"No se encontró la columna de parentesco (P6050 o P6051).")

        # FILTRO: Aislamos al Jefe(a) de Hogar usando la columna detectada
        df_jefe = df_pers[df_pers[col_parentesco] == '1'].copy()

        # Conservamos las llaves y las variables demográficas confirmadas (Sexo y Edad)
        df_jefe_filtrado = df_jefe[['DIRECTORIO', 'P6020', 'P6040']].copy()
        df_jefe_filtrado['ANIO'] = str(anio)

        # Eliminamos duplicados por si acaso
        df_jefe_filtrado = df_jefe_filtrado.drop_duplicates(subset=['DIRECTORIO', 'ANIO'])

        dfs_jefes_listos.append(df_jefe_filtrado)
        print(f"✅ Jefes de hogar extraídos para el año {anio} usando parentesco: '{col_parentesco}'")

    except Exception as e:
        print(f"❌ Error al procesar el año {anio}: {e}")

# 3. Consolidamos el histórico demográfico
df_jefes_historico = pd.concat(dfs_jefes_listos, ignore_index=True)

# Limpieza preventiva en df_limpio por si ya existían columnas de intentos previos
for col in ['P6020', 'P6040']:
    if col in df_limpio.columns:
        df_limpio = df_limpio.drop(columns=[col])

# 4. El MERGE definitivo con tu base analítica principal
df_limpio = pd.merge(
    df_limpio,
    df_jefes_historico,
    on=['DIRECTORIO', 'ANIO'],
    how='left'
)

print("\n📊 ¡INTEGRACIÓN DEMOGRÁFICA HISTÓRICA EXITOSA!")
print(f"Dimensiones actuales del dataset maestro: {df_limpio.shape}")
print("\nValidación de nulos demográficos por año (El objetivo es 0 nulos):")
print(df_limpio.groupby('ANIO')[['P6020', 'P6040']].apply(lambda x: x.isna().sum()))

import pandas as pd

# 1. Estandarización y mapeo de las variables demográficas crudas
# En el DANE: 1 = Hombre, 2 = Mujer
df_limpio['SEXO_JEFE'] = df_limpio['P6020'].map({'1': 'Hombre', '2': 'Mujer'}).fillna('No Reportado')
df_limpio['EDAD_JEFE'] = pd.to_numeric(df_limpio['P6040'], errors='coerce')

# Filtramos para analizar la foto demográfica más reciente
df_2025_demo = df_limpio[df_limpio['ANIO'] == '2025'].copy()

# 2. Análisis A: Tasa de Inseguridad Alimentaria Grave por Género de la Jefatura
brecha_genero = df_2025_demo.groupby('SEXO_JEFE').apply(
    lambda x: pd.Series({
        'Inseguridad_Grave_%': (x['PIAG_DUMMY'] * x['FEX_C']).sum() / x['FEX_C'].sum() * 100,
        'Muestra_Hogares_Encuestados': len(x)
    }), include_groups=False
).reset_index()

# 3. Análisis B: Mediana de edad de los jefes de hogar
# Comparamos hogares estables frente a hogares en situación de hambre extrema
mediana_edad = df_2025_demo.groupby('PIAG_DUMMY').apply(
    lambda x: pd.Series({
        'Mediana_Edad_Jefe': x['EDAD_JEFE'].median()
    }), include_groups=False
).reset_index()

# Mapeamos la variable dummy para que el reporte sea legible
mediana_edad['Condición del Hogar'] = mediana_edad['PIAG_DUMMY'].map({
    0: 'Hogares con Seguridad o Inseguridad Moderada',
    1: 'Hogares con Inseguridad Alimentaria Grave 🚨'
})

print("📊 1. BRECHA DE GÉNERO EN INSEGURIDAD ALIMENTARIA GRAVE (2025):")
print(brecha_genero.to_string(index=False))

print("\n📊 2. MEDIANA DE EDAD DEL JEFE DE HOGAR SEGÚN SU CONDICIÓN (2025):")
print(mediana_edad[['Condición del Hogar', 'Mediana_Edad_Jefe']].to_string(index=False))

import pandas as pd
import os
import unicodedata

# Función auxiliar para eliminar tildes y estandarizar nombres de archivos
def normalizar(texto):
    return ''.join(c for c in unicodedata.normalize('NFD', texto) if unicodedata.category(c) != 'Mn').lower()

# Buscador inteligente en la carpeta de Colab
def buscar_archivo_dinamico(anio, palabra_clave):
    archivos = os.listdir('/content')
    for f in archivos:
        f_norm = normalizar(f)
        if str(anio) in f_norm and normalizar(palabra_clave) in f_norm and f.lower().endswith('.csv'):
            return os.path.join('/content', f)
    return None

# --- 1. REPARACIÓN DEL DATASET INFLADO ---
if df_limpio.shape[0] > 347180:
    print("⚠️ Detectamos duplicados del intento anterior. Iniciando reparación...")
    for col_eliminar in ['EDU_RAW', 'NIVEL_EDUCATIVO']:
        if col_eliminar in df_limpio.columns:
            df_limpio = df_limpio.drop(columns=[col_eliminar])
    # Restauramos el dataset a sus hogares únicos originales
    df_limpio = df_limpio.drop_duplicates(subset=['DIRECTORIO', 'ANIO'])
    print(f"✅ Dataset maestro reparado con éxito. Filas devueltas a: {df_limpio.shape[0]}")

# --- 2. PIPELINE DE EXTRACCIÓN ADAPTATIVA ---
dfs_educacion_jefes = []
print("\n⏳ Iniciando escaneo dinámico de capital humano (sin importar tildes o mayúsculas)...")

for anio in [2022, 2023, 2024, 2025]:
    try:
        # Buscamos los caminos reales usando el detector inteligente
        path_comp = buscar_archivo_dinamico(anio, "composicion")
        path_edu = buscar_archivo_dinamico(anio, "educacion")

        if not path_comp or not path_edu:
            raise FileNotFoundError(f"No se encontró el archivo de composición o educación para el año {anio}")

        # A. Procesamos Composición para capturar las llaves del jefe (DIRECTORIO + ORDEN)
        df_comp = pd.read_csv(path_comp, sep=";", encoding="latin-1", dtype=str)
        df_comp.columns = df_comp.columns.str.upper()

        # Buscador de la columna de parentesco (P6050 o P6051)
        col_parentesco = 'P6051' if 'P6051' in df_comp.columns else 'P6050'
        df_jefe_llaves = df_comp[df_comp[col_parentesco] == '1'][['DIRECTORIO', 'ORDEN']].copy()
        df_jefe_llaves = df_jefe_llaves.drop_duplicates(subset=['DIRECTORIO']) # Blindaje anti-duplicados

        # B. Procesamos el módulo de Educación
        df_edu = pd.read_csv(path_edu, sep=";", encoding="latin-1", dtype=str)
        df_edu.columns = df_edu.columns.str.upper()

        # Detectamos si el año usa P6210 o P8587
        col_edu_encontrada = 'P8587' if 'P8587' in df_edu.columns else 'P6210'
        df_edu_filtrado = df_edu[['DIRECTORIO', 'ORDEN', col_edu_encontrada]].copy()
        df_edu_filtrado = df_edu_filtrado.drop_duplicates(subset=['DIRECTORIO', 'ORDEN']) # Blindaje por persona

        # C. Cruzamos para extraer la educación exclusiva del jefe de hogar
        df_jefe_edu = pd.merge(df_jefe_llaves, df_edu_filtrado, on=['DIRECTORIO', 'ORDEN'], how='inner')
        df_jefe_edu = df_jefe_edu.rename(columns={col_edu_encontrada: 'EDU_RAW'})
        df_jefe_edu['ANIO'] = str(anio)

        dfs_educacion_jefes.append(df_jefe_edu[['DIRECTORIO', 'ANIO', 'EDU_RAW']])
        print(f"✅ Año {anio} indexado correctamente usando: '{col_edu_encontrada}'")

    except Exception as e:
        print(f"❌ Error crítico en el año {anio}: {e}")

# --- 3. CONSOLIDACIÓN E INYECCIÓN EN EL DATASET MAESTRO ---
df_edu_historico = pd.concat(dfs_educacion_jefes, ignore_index=True)
df_edu_historico = df_edu_historico.drop_duplicates(subset=['DIRECTORIO', 'ANIO']) # Último filtro de seguridad

df_limpio = pd.merge(df_limpio, df_edu_historico, on=['DIRECTORIO', 'ANIO'], how='left')

# Mapeo oficial homologado
dicc_educacion = {
    '1': 'Ninguno', '2': 'Preescolar', '3': 'Básica primaria',
    '4': 'Básica secundaria', '5': 'Media (Bachillerato)',
    '6': 'Superior o Universitaria', '9': 'No sabe/No responde'
}
df_limpio['NIVEL_EDUCATIVO'] = df_limpio['EDU_RAW'].map(dicc_educacion).fillna('No Reportado')

print("\n📊 ¡PIPELINE DE CAPITAL HUMANO TERMINADO EXITOSAMENTE!")
print(f"Dimensiones finales del dataset maestro (Debe ser 347180 filas): {df_limpio.shape}")

import pandas as pd

# 1. Aseguramos que los factores de expansión y la variable dummy sean numéricos
df_limpio['FEX_C'] = pd.to_numeric(df_limpio['FEX_C'], errors='coerce')
df_limpio['PIAG_DUMMY'] = pd.to_numeric(df_limpio['PIAG_DUMMY'], errors='coerce')

# 2. Filtramos la foto más reciente (Año 2025)
df_2025_edu = df_limpio[df_limpio['ANIO'] == '2025'].copy()

# 3. Calculamos la tasa de Inseguridad Alimentaria Grave ponderada por nivel educativo del jefe
reporte_educacion = df_2025_edu.groupby('NIVEL_EDUCATIVO').apply(
    lambda x: pd.Series({
        'Inseguridad_Grave_%': (x['PIAG_DUMMY'] * x['FEX_C']).sum() / x['FEX_C'].sum() * 100,
        'Hogares_en_Muestra': len(x)
    }), include_groups=False
).reset_index()

# 4. Ordenamos de mayor a menor vulnerabilidad
reporte_educacion = reporte_educacion.sort_values(by='Inseguridad_Grave_%', ascending=False)

print("🎓 RELACIÓN ENTRE EL NIVEL EDUCATIVO DEL JEFE Y EL HAMBRE EXTREMA (2025):")
print(reporte_educacion.to_string(index=False))

# Exportamos el dataset consolidado listo para Power BI
# (utf-8-sig incluye BOM, compatible tanto con Power BI como con Excel)
df_limpio.to_csv("ECV_Hambre_Colombia_2022_2025.csv", index=False, sep=";", encoding="utf-8-sig")